{% set name = "pythonnet" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d4b2e97158a023875f8647458a58f38817f4fe39af60abdd6b0d8adf1d77e75

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - dotnet-sdk
  host:
    - pip
    - python >=3.7,<3.13
    - setuptools >=61
    - wheel
  run:
    - clr_loader >=0.2.6,<0.3.0
    - python >=3.7,<3.13

test:
  imports:
    - clr
  requires:
    - dotnet-runtime
    - importlib_resources
    - pip
    - mono
  commands:
    - pip check

about:
  home: http://pythonnet.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: .Net and Mono integration for Python
  description: |
    Python for .NET is a package that gives Python programmers nearly seamless integration with the
     .NET Common Language Runtime (CLR) and provides a powerful application scripting tool for .NET
      developers.
  dev_url: https://github.com/pythonnet/pythonnet

extra:
  recipe-maintainers:
    - m-rossi
    - bgruening
